'use client';

import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { usePathname } from 'next/navigation';
import Sponsors from '@/components/layout/Sponsors';
import './globals.css';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const isAdmin = pathname.startsWith('/admin');
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <head>
          <title>NK Tolmin</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/tolmin-logo.png" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}

          {/* Hide Sponsors and footer when on admin pages */}
          {!isAdmin && <Sponsors />}
          {!isAdmin && (
            <div className="w-full p-5 bg-red-600 text-gray-200 poppins flex items-center justify-between">
              <div className="flex gap-5 text-sm -mb-1">
                <p>(c) 2018, Tolmin Football Club</p>
                <p>Legal notice and cookies | Website development</p>
              </div>
              <div className='flex gap-4'>
                <Image src="/logo/instagram.png" alt="Instagram" width={25} height={25} />
                <Image src="/logo/facebook.png" alt="Facebook" width={25} height={25} />
                <Image src="/logo/youtube.png" alt="YouTube" width={25} height={25} />
                <Image src="/logo/linkedin.png" alt="LinkedIn" width={25} height={25} />
              </div>
            </div>
          )}
        </body>
      </html>
    </QueryClientProvider>
  );
}
